<a href="https://colab.research.google.com/github/leikcaro/Wines/blob/main/Wine_tarea.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

Mounted at /content/drive


In [ ]:
filename = '/content/drive/MyDrive/Coding Dojo/Semana 7/wine.csv'
col_names = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols',
'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins','Color intensity', 'Hue', 'OD280/OD315 of diluted wines','Proline']
### Figure this out!
df = pd.read_csv(filename, header = None,names = col_names)
df


Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0              1    14.23        1.71  2.43               15.6        127   
1              1    13.20        1.78  2.14               11.2        100   
2              1    13.16        2.36  2.67               18.6        101   
3              1    14.37        1.95  2.50               16.8        113   
4              1    13.24        2.59  2.87               21.0        118   
..           ...      ...         ...   ...                ...        ...   
173            3    13.71        5.65  2.45               20.5         95   
174            3    13.40        3.91  2.48               23.0        102   
175            3    13.27        4.28  2.26               20.0        120   
176            3    13.17        2.59  2.37               20.0        120   
177            3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Class label                   178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

In [ ]:
# Imprimir cuántas clases
print('Class labels', np.unique(df['Class label']))

Class labels [1 2 3]


In [ ]:
# Las clases no están equilibradas
df['Class label'].value_counts(dropna = False)

2    71
1    59
3    48
Name: Class label, dtype: int64

In [ ]:
# Organizar los datos en la matriz de características y el vector de destino
X = df.loc[:, df.columns[(df.columns != 'Class label')]]
y = df.loc[:, 'Class label'].values

In [ ]:
# En encuestas estadísticas,
# cuando las subpoblaciones dentro de una población general varían,
# Podría ser ventajoso muestrear cada subpoblación (estrato) de forma independiente
# La estratificación es el proceso de dividir a los miembros de la población en subgrupos homogéneos antes
# del muestreo.
#help(train_test_split)

In [ ]:
# Dividir en conjuntos de prueba y entrenamiento
# Proporcionar la matriz de etiquetas de clase y como argumento para estratificar asegura a ambos
# el conjunto de entrenamiento y los conjuntos de datos de prueba tienen las mismas proporciones de clase que el
# conjunto de datos original
X_train, X_test, y_train, y_test =train_test_split(X,
                                                   y,
                                                   test_size=0.3, 
                                                   random_state=0, 
                                                   stratify=y)

In [ ]:
unique, counts = np.unique(y_train, return_counts=True)
dict(zip(unique, counts))

{1: 41, 2: 50, 3: 33}

In [ ]:
# Estandarizar datos
scaler = StandardScaler()
# Ajustar solo al conjunto de entrenamiento
scaler.fit(X_train)
# Aplicar  transform tanto al conjunto de entrenamiento como al conjunto de prueba
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
log_reg = LogisticRegression(penalty='l1',
                        C=1.0,
                        solver='liblinear',
                        multi_class='ovr')
log_reg.fit(X_train, y_train)
print('Training accuracy:', log_reg.score(X_train, y_train))
print('Test accuracy:', log_reg.score(X_test, y_test))

Training accuracy: 1.0
Test accuracy: 1.0


In [ ]:
log_reg.intercept_

array([-1.26372726, -1.21539909, -2.36997344])

In [ ]:
log_reg.coef_

array([[ 1.24613047,  0.1800259 ,  0.74631354, -1.16404157,  0.        ,
         0.        ,  1.15933335,  0.        ,  0.        ,  0.        ,
         0.        ,  0.55692512,  2.50887876],
       [-1.53756672, -0.38705977, -0.99594067,  0.36566093, -0.05947683,
         0.        ,  0.66766245,  0.        ,  0.        , -1.93339627,
         1.23464761,  0.        , -2.23135186],
       [ 0.1356201 ,  0.16871418,  0.35714854,  0.        ,  0.        ,
         0.        , -2.43761641,  0.        ,  0.        ,  1.56374212,
        -0.81880876, -0.49287025,  0.        ]])

In [ ]:
# La primera clase es la puntuación más alta, por lo que será la predicción 0 (la primera clase) para estos datos
log_reg.predict_proba(X_test[0:1])

array([[9.76603849e-01, 4.48187975e-04, 2.29479629e-02]])

In [ ]:
# También podemos obtener la clase asociada con la probabilidad más alta
log_reg.predict(X_test[0:1])

array([1])

In [ ]:
log_reg = LogisticRegression(penalty='l2',
                        C=1.0,
                        solver='liblinear',
                        multi_class='ovr')
log_reg.fit(X_train, y_train)
print('Training accuracy:', log_reg.score(X_train, y_train))
print('Test accuracy:', log_reg.score(X_test, y_test))
#al usar penalty l2 disminuye ligeramente la prediccion

Training accuracy: 0.9919354838709677
Test accuracy: 1.0


In [ ]:
#para el caso de usar multinomial, no permite usar el solver anterior y solo permite usar el l2 como penalizador, pero tambien logro un training y test accuracy perfecto
log_reg = LogisticRegression(penalty='l2',
                        C=1.0,
                        solver='lbfgs',
                        multi_class='multinomial')
log_reg.fit(X_train, y_train)
print('Training accuracy:', log_reg.score(X_train, y_train))
print('Test accuracy:', log_reg.score(X_test, y_test))
#al usar penalty l2 disminuye ligeramente la prediccion

Training accuracy: 1.0
Test accuracy: 1.0


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
grid = { 
    'n_estimators': [2,4,6,8,10,12,15,17,20],
    'max_features': ['sqrt', 'log2'],
    'max_depth' : [2,3,4,5,6,7,8],
    'criterion' :['gini', 'entropy'],
    'random_state' : [18]
}
forest_clf = RandomForestClassifier()



grid_search = GridSearchCV(forest_clf, grid, cv=4,
                          return_train_score=True)

grid_search.fit(X_train, y_train)

GridSearchCV(cv=4, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [2, 4, 6, 8, 10, 12, 15, 17, 20],
                         'random_state': [18]},
             return_train_score=True)

In [ ]:
cvres = grid_search.cv_results_
print(cvres['mean_test_score'], cvres['params'])

[0.83870968 0.87903226 0.88709677 0.87903226 0.92741935 0.94354839
 0.93548387 0.94354839 0.95967742 0.83870968 0.87903226 0.88709677
 0.87903226 0.92741935 0.94354839 0.93548387 0.94354839 0.95967742
 0.88709677 0.92741935 0.95967742 0.96774194 0.96774194 0.93548387
 0.93548387 0.9516129  0.95967742 0.88709677 0.92741935 0.95967742
 0.96774194 0.96774194 0.93548387 0.93548387 0.9516129  0.95967742
 0.86290323 0.91935484 0.94354839 0.9516129  0.9516129  0.9516129
 0.9516129  0.9516129  0.95967742 0.86290323 0.91935484 0.94354839
 0.9516129  0.9516129  0.9516129  0.9516129  0.9516129  0.95967742
 0.90322581 0.93548387 0.95967742 0.95967742 0.94354839 0.9516129
 0.9516129  0.94354839 0.95967742 0.90322581 0.93548387 0.95967742
 0.95967742 0.94354839 0.9516129  0.9516129  0.94354839 0.95967742
 0.90322581 0.93548387 0.95967742 0.95967742 0.94354839 0.9516129
 0.9516129  0.94354839 0.95967742 0.90322581 0.93548387 0.95967742
 0.95967742 0.94354839 0.9516129  0.9516129  0.94354839 0.9596774

In [ ]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 3,
 'max_features': 'sqrt',
 'n_estimators': 8,
 'random_state': 18}

In [ ]:
grid_search.best_score_

0.967741935483871

In [ ]:
grid_search.score(X_test, y_test)

1.0

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
grid2 = { 
    'n_neighbors': [2, 3, 4, 5, 6, 7, 8,9,10],
    'weights': ['uniform', 'distance'],
    'leaf_size' : [4,5,6,7,8,9,10,15,20,25,30,40,50],
    }
knn_clf = KNeighborsClassifier()



grid_search2 = GridSearchCV(knn_clf, grid2, cv=4,
                          return_train_score=True)

grid_search2.fit(X_train, y_train)

GridSearchCV(cv=4, estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 40,
                                       50],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'weights': ['uniform', 'distance']},
             return_train_score=True)

In [ ]:
grid_search2.best_params_

{'leaf_size': 4, 'n_neighbors': 8, 'weights': 'uniform'}

In [ ]:
grid_search2.best_score_

0.9596774193548387

In [ ]:
grid_search2.score(X_test, y_test)

0.9629629629629629

¿Qué modelo funcionó mejor?

Funcionó mejor el modelo de random forest

¿Cuáles son las características más importantes de tus modelos? ¿Hay algún modelo que te haya gustado más y por qué?


En general me gusta mucho el modelo de random forest, con gridsearch, es muy potente, no necesita escalamientos, sirve para todo tipo de problemas y es interpretable.